INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE , IMG_PATH)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',1,1 , '/images/pexels-photo-220453.jpeg');

INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',2,1);

INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',3,1);

INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',4,1);

INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',5,1);

INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',6,1);

INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',7,1);

INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',8,1);

INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',9,1);


INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',10,1);


INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',11,1);


INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',12,1);


INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',13,1);


INSERT INTO TEACHER(NAME,SURNAME,AGE,TEACH_LESSON,EXPERIENCE,DEGREE,STREET,CITY,COUNTRY,ACTIVE)
VALUES('VELI','KAZIMOV',45,'FIZIKA',10,'PROFESSOR','R.SABIROV','BAKU','AZERBAIJAN',1);

INSERT INTO STUDENT(NAME,SURNAME,AGE,COURSE,EXAM_POINT,STREET,CITY,COUNTRY,TEACHER_ID,ACTIVE)
VALUES('SAMIR','SAMIROV',23,3,652,'Y.ELIYEV','BAKU','AZERBAIJAN',14,1);
